In [1]:
# ============================================
# 0. 설치
# ============================================
!pip -q install transformers accelerate datasets tqdm

import os
import gc
import zipfile
import numpy as np
import pandas as pd
import torch
from tqdm.auto import tqdm
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from google.colab import files

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

Device: cuda

In [2]:
# ============================================
# 1. 새 전처리 파일 업로드
# ============================================
uploaded = files.upload()

# 파일명이 modified_preprocessing.csv인지 확인
print(os.listdir())

Saving modified_preprocessing.csv to modified_preprocessing.csv
['.config', 'modified_preprocessing.csv', 'sample_data']

In [3]:
# ============================================
# 2. 데이터 불러오기
# ============================================
DATA_PATH = "modified_preprocessing.csv"

df = pd.read_csv(DATA_PATH)

df["created_time"] = pd.to_datetime(df["created_time"], errors="coerce")
df["Date"] = df["created_time"].dt.date

df["cleaned_text"] = df["cleaned_text"].fillna("").astype(str)
df = df[df["cleaned_text"].str.strip() != ""].copy()

# 너무 긴 댓글은 모델 입력 제한 때문에 적당히 자르기
df["text_for_model"] = df["cleaned_text"].str.slice(0, 1000)

print(df.shape)
display(df[["Date", "cleaned_text"]].head())
print(df["Date"].min(), df["Date"].max())

(55473, 27)

         Date                                       cleaned_text
0  2023-11-07  Palestinians are so anti-jewish that hamas' pu...
1  2023-11-07  War is bad,hamas started this and then ran to ...
2  2023-11-07  I don’t deny that Hamas is also pursuing a pol...
3  2023-11-07  Yes, why would they put their soldiers in harm...
4  2023-11-07  Israel is not allowed to root out Hamas, they ...

2023-09-07 2023-11-07

In [4]:
# ============================================
# 3. 사용할 모델 목록
# ============================================
MODEL_CONFIGS = [
    {
        "name": "bert_goemotions",
        "model_id": "monologg/bert-base-cased-goemotions-original",
        "type": "goemotions"
    },
    {
        "name": "distilbert_goemotions",
        "model_id": "joeddav/distilbert-base-uncased-go-emotions-student",
        "type": "goemotions"
    },
    {
        "name": "distilroberta_goemotions",
        "model_id": "SamLowe/roberta-base-go_emotions",
        "type": "goemotions"
    },
    {
        "name": "modernbert_goemotions",
        "model_id": "answerdotai/ModernBERT-base",
        "type": "goemotions"
    },
    {
        "name": "twitter_roberta",
        "model_id": "cardiffnlp/twitter-roberta-base-sentiment-latest",
        "type": "sentiment"
    }
]

In [5]:
# ============================================
# 4. 감정분석 함수
# ============================================
def run_model_daily(df, model_name, model_id, model_type, batch_size=32):
    print("=" * 80)
    print(f"Running model: {model_name}")
    print(f"Model ID: {model_id}")

    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForSequenceClassification.from_pretrained(model_id)
    model.to(device)
    model.eval()

    id2label = model.config.id2label
    labels = [id2label[i] for i in range(len(id2label))]
    labels = [str(x).lower() for x in labels]

    print("Labels:", labels)

    texts = df["text_for_model"].tolist()
    dates = df["Date"].tolist()

    all_scores = []

    for i in tqdm(range(0, len(texts), batch_size)):
        batch_texts = texts[i:i+batch_size]

        inputs = tokenizer(
            batch_texts,
            padding=True,
            truncation=True,
            max_length=512,
            return_tensors="pt"
        )

        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = model(**inputs)
            logits = outputs.logits

        # GoEmotions는 보통 multi-label이라 sigmoid
        # Twitter sentiment는 positive/neutral/negative라 softmax
        if model_type == "goemotions":
            probs = torch.sigmoid(logits)
        else:
            probs = torch.softmax(logits, dim=-1)

        all_scores.append(probs.cpu().numpy())

    all_scores = np.vstack(all_scores)

    score_df = pd.DataFrame(all_scores, columns=labels)
    score_df["Date"] = dates

    # 날짜별 평균 감정 점수
    daily = score_df.groupby("Date")[labels].mean().reset_index()

    # 날짜별 댓글 수
    counts = df.groupby("Date").size().reset_index(name="comment_count")
    daily = daily.merge(counts, on="Date", how="left")

    # 저장
    output_name = f"{model_name}_daily.csv"
    daily.to_csv(output_name, index=False)

    print(f"Saved: {output_name}")
    display(daily.head())

    del tokenizer, model
    torch.cuda.empty_cache()
    gc.collect()

    return daily

In [6]:
# ============================================
# 4. 감정분석 함수
# ============================================
def run_model_daily(df, model_name, model_id, model_type, batch_size=32):
    print("=" * 80)
    print(f"Running model: {model_name}")
    print(f"Model ID: {model_id}")

    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForSequenceClassification.from_pretrained(model_id)
    model.to(device)
    model.eval()

    id2label = model.config.id2label
    labels = [id2label[i] for i in range(len(id2label))]
    labels = [str(x).lower() for x in labels]

    print("Labels:", labels)

    texts = df["text_for_model"].tolist()
    dates = df["Date"].tolist()

    all_scores = []

    for i in tqdm(range(0, len(texts), batch_size)):
        batch_texts = texts[i:i+batch_size]

        inputs = tokenizer(
            batch_texts,
            padding=True,
            truncation=True,
            max_length=512,
            return_tensors="pt"
        )

        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = model(**inputs)
            logits = outputs.logits

        # GoEmotions는 보통 multi-label이라 sigmoid
        # Twitter sentiment는 positive/neutral/negative라 softmax
        if model_type == "goemotions":
            probs = torch.sigmoid(logits)
        else:
            probs = torch.softmax(logits, dim=-1)

        all_scores.append(probs.cpu().numpy())

    all_scores = np.vstack(all_scores)

    score_df = pd.DataFrame(all_scores, columns=labels)
    score_df["Date"] = dates

    # 날짜별 평균 감정 점수
    daily = score_df.groupby("Date")[labels].mean().reset_index()

    # 날짜별 댓글 수
    counts = df.groupby("Date").size().reset_index(name="comment_count")
    daily = daily.merge(counts, on="Date", how="left")

    # 저장
    output_name = f"{model_name}_daily.csv"
    daily.to_csv(output_name, index=False)

    print(f"Saved: {output_name}")
    display(daily.head())

    del tokenizer, model
    torch.cuda.empty_cache()
    gc.collect()

    return daily

In [7]:
# ============================================
# 5. 전체 모델 한 번에 실행
# ============================================
daily_results = {}

for config in MODEL_CONFIGS:
    try:
        daily = run_model_daily(
            df=df,
            model_name=config["name"],
            model_id=config["model_id"],
            model_type=config["type"],
            batch_size=32
        )
        daily_results[config["name"]] = daily

    except Exception as e:
        print("=" * 80)
        print(f"ERROR in {config['name']}")
        print(e)
        print("이 모델은 건너뛰고 다음 모델로 넘어감.")
        torch.cuda.empty_cache()
        gc.collect()

================================================================================
Running model: bert_goemotions
Model ID: monologg/bert-base-cased-goemotions-original

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.67k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/235 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/182 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/433M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Labels: ['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral']

  0%|          | 0/1734 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

Saved: bert_goemotions_daily.csv

,Date,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral,comment_count
0,2023-09-07,0.055264,0.060238,0.021548,0.028444,0.090360,0.008320,0.023216,0.151419,0.007354,...,0.001097,0.025519,0.006444,0.020316,0.003618,0.036262,0.026156,0.019027,0.519095,91
1,2023-09-08,0.027197,0.031046,0.020865,0.007922,0.084945,0.027176,0.082826,0.098919,0.003036,...,0.001672,0.019961,0.000841,0.022546,0.001481,0.023767,0.038716,0.018621,0.562920,40
2,2023-09-09,0.002479,0.107653,0.223332,0.169612,0.017196,0.063832,0.003505,0.036086,0.002864,...,0.000995,0.015014,0.000787,0.035006,0.001133,0.002400,0.057458,0.052733,0.336598,19
3,2023-09-10,0.062857,0.039872,0.044741,0.022484,0.089568,0.002182,0.026512,0.016988,0.001131,...,0.003210,0.003730,0.001061,0.081109,0.000910,0.001465,0.023031,0.060695,0.580480,52
4,2023-09-11,0.038255,0.006140,0.059708,0.056855,0.078030,0.019412,0.033481,0.068108,0.003960,...,0.007947,0.036652,0.002651,0.071688,0.003042,0.015437,0.101528,0.039489,0.456371,239

================================================================================
Running model: distilbert_goemotions
Model ID: joeddav/distilbert-base-uncased-go-emotions-student

config.json:   0%|          | 0.00/1.75k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/421 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Labels: ['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral']

  0%|          | 0/1734 [00:00<?, ?it/s]

Saved: distilbert_goemotions_daily.csv

,Date,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral,comment_count
0,2023-09-07,0.314362,0.384552,0.469495,0.532020,0.473203,0.540720,0.644536,0.663572,0.541115,...,0.414194,0.290153,0.399402,0.602378,0.363586,0.505067,0.390058,0.560139,0.359078,91
1,2023-09-08,0.331895,0.380445,0.469473,0.501364,0.498856,0.549533,0.640451,0.636639,0.564817,...,0.428794,0.269670,0.386234,0.595641,0.370812,0.516753,0.363170,0.556054,0.361506,40
2,2023-09-09,0.220228,0.317186,0.598160,0.605695,0.429394,0.434374,0.680494,0.563052,0.570129,...,0.462189,0.208366,0.329942,0.501501,0.277235,0.518687,0.474606,0.510744,0.320997,19
3,2023-09-10,0.327079,0.407386,0.502306,0.513368,0.484626,0.519625,0.572732,0.625718,0.557488,...,0.452094,0.291785,0.396201,0.605448,0.346274,0.489993,0.379535,0.558925,0.333389,52
4,2023-09-11,0.272072,0.282646,0.492308,0.508497,0.475829,0.508681,0.597456,0.598014,0.542305,...,0.376095,0.232692,0.343433,0.596320,0.302311,0.544585,0.530099,0.524628,0.332449,239

================================================================================
Running model: distilroberta_goemotions
Model ID: SamLowe/roberta-base-go_emotions

config.json:   0%|          | 0.00/1.92k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/380 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.11M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Labels: ['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral']

  0%|          | 0/1734 [00:00<?, ?it/s]

Saved: distilroberta_goemotions_daily.csv

,Date,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral,comment_count
0,2023-09-07,0.055688,0.060865,0.014677,0.029155,0.086477,0.005104,0.071222,0.108346,0.004364,...,0.001761,0.020169,0.001606,0.026798,0.001617,0.019215,0.032719,0.013564,0.469708,91
1,2023-09-08,0.050428,0.012631,0.006219,0.033290,0.094011,0.020677,0.092415,0.066424,0.005036,...,0.002148,0.025498,0.000885,0.027943,0.001445,0.017931,0.028862,0.012445,0.508189,40
2,2023-09-09,0.006601,0.098592,0.125231,0.166224,0.045633,0.008368,0.018249,0.064506,0.005060,...,0.001480,0.041957,0.001137,0.022444,0.003554,0.001599,0.053805,0.033330,0.351097,19
3,2023-09-10,0.069570,0.033337,0.025482,0.026860,0.075323,0.019271,0.021889,0.016839,0.001870,...,0.003510,0.005860,0.000938,0.039908,0.001313,0.001114,0.024441,0.045219,0.568053,52
4,2023-09-11,0.032498,0.009617,0.042403,0.062045,0.081281,0.011857,0.046581,0.046237,0.007689,...,0.006751,0.034222,0.001109,0.043178,0.002274,0.011306,0.089034,0.024257,0.422633,239

================================================================================
Running model: modernbert_goemotions
Model ID: answerdotai/ModernBERT-base

config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/20.8k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.13M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/599M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Labels: ['label_0', 'label_1']

  0%|          | 0/1734 [00:00<?, ?it/s]

Saved: modernbert_goemotions_daily.csv

         Date   label_0   label_1  comment_count
0  2023-09-07  0.500372  0.483798             91
1  2023-09-08  0.504411  0.452467             40
2  2023-09-09  0.476794  0.437692             19
3  2023-09-10  0.527066  0.504270             52
4  2023-09-11  0.501302  0.494539            239

================================================================================
Running model: twitter_roberta
Model ID: cardiffnlp/twitter-roberta-base-sentiment-latest

config.json:   0%|          | 0.00/929 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/501M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Labels: ['negative', 'neutral', 'positive']

  0%|          | 0/1734 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/501M [00:00<?, ?B/s]

Saved: twitter_roberta_daily.csv

         Date  negative   neutral  positive  comment_count
0  2023-09-07  0.454486  0.396909  0.148604             91
1  2023-09-08  0.499195  0.393306  0.107498             40
2  2023-09-09  0.720283  0.244823  0.034894             19
3  2023-09-10  0.456667  0.387956  0.155377             52
4  2023-09-11  0.601146  0.307927  0.090927            239

In [8]:
# ============================================
# 6. 생성된 파일 확인
# ============================================
daily_files = [f for f in os.listdir() if f.endswith("_daily.csv")]
daily_files

['modernbert_goemotions_daily.csv',
 'distilroberta_goemotions_daily.csv',
 'bert_goemotions_daily.csv',
 'distilbert_goemotions_daily.csv',
 'twitter_roberta_daily.csv']

In [9]:
# ============================================
# 7. 결과 파일 zip으로 묶어서 다운로드
# ============================================
zip_name = "new_emotion_daily_results.zip"

with zipfile.ZipFile(zip_name, "w") as zipf:
    for f in daily_files:
        zipf.write(f)

files.download(zip_name)